### PR TITLE
make time-zone aware

### PR DESCRIPTION
**Pull request by phiresky**
companion PR to https://github.com/LemmyNet/lemmy/pull/3496 

Replaces all instances of NaiveDateTime with DateTime<Utc>

### CODE REVIEW

**Review by Nutomic — COMMENTED** [review]
Looks good, unfortunately it will require a breaking change.

You also need to run `cargo +nightly fmt`

**Comment by dessalines** [comment]
Format check failing.

**Comment by Nutomic** [comment]
```

error: useless conversion to the same type: `chrono::DateTime<chrono::Utc>`
   --> src/fetch/object_id.rs:263:40
    |
263 |         assert!(!should_refetch_object(one_second_ago.into()));
    |                                        ^^^^^^^^^^^^^^^^^^^^^ help: consider removing `.into()`: `one_second_ago`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
    = note: `-D clippy::useless-conversion` implied by `-D clippy::complexity`

error: useless conversion to the same type: `chrono::DateTime<chrono::Utc>`
   --> src/fetch/object_id.rs:266:39
    |
266 |         assert!(should_refetch_object(two_days_ago.into()));
    |                                       ^^^^^^^^^^^^^^^^^^^ help: consider removing `.into()`: `two_days_ago`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
```

**Comment by Nutomic** [comment]
Still failing on clippy step.

**Comment by phiresky** [comment]
woodpecker ran with the wrong commit again -.-. fixed with an empty commit.

**Review by Nutomic — APPROVED** [review]

**Pull request merged**
