### PR TITLE
chore: update .gitignore

### PR DESCRIPTION
**Pull request by kwaa**
~~Set up a minimal devShell. (flake + nix-direnv)~~

~~This applies to everyone who uses the [`nix`](https://nixos.org/download/) package manager and facilitates my next (possible) contribution. (https://github.com/importantimport/hatsu/issues/50)~~

Update .gitignore to ignore nix flake files.

### CODE REVIEW

**Comment by kwaa** [comment]
cc @Nutomic 

I'm unsure what the CI failed for.

**Comment by Nutomic** [comment]
I dont use nix so I wouldnt be able to maintain this. Anyway its a completely standard Rust project, why would you need some special config as part of the repo?

**Comment by kwaa** [comment]
> I dont use nix so I wouldnt be able to maintain this. Anyway its a completely standard Rust project, why would you need some special config as part of the repo?

I'm using NixOS and need devShell to get the `rust-analyzer` to work properly on VSCode.

It's a simple stable toolchain that doesn't require much maintenance.

Alternatively, it might be possible to add `flake.{nix,lock}` and `.envrc` to `.gitignores` so that I can open PR without committing those files.

**Comment by Nutomic** [comment]
Yes I prefer adjusting gitignore.

**Comment by kwaa** [comment]
> Yes I prefer adjusting gitignore.

Okay, I've updated PR.

**Comment by Nutomic** [comment]
Thanks, but please put some comments what these gitignore lines are for. The CI failure is not yours, a test is trying to connect to a broken server. Gonna fix it soon.

**Comment by kwaa** [comment]
> Thanks, but please put some comments what these gitignore lines are for.

done

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
Thanks!

**Pull request merged**
